# render.yaml
# Este archivo le indica a Render cómo desplegar tu aplicación.
# Colócalo en la raíz de tu repositorio.

services:
  # Define un servicio de tipo "Sitio Estático"
  - type: static_site
    # El nombre que tendrá tu servicio en Render
    name: submarinos-monitoring-frontend
    # La rama de tu repositorio que se desplegará
    branch: main
    # El directorio raíz que contiene tus archivos estáticos (index.html, app.js, etc.)
    # Asegúrate de que esta ruta sea correcta para tu proyecto.
    rootDir: public